---


version: '2.3'


################################################################################
# SERVICES
################################################################################
services:


  # ------------------------------------------------------------
  # PHP
  # ------------------------------------------------------------
  php:
    image: devilbox/php-fpm:8.0-work-0.130
    env_file:
        - ./.env-docker-compose
    volumes:
        - .:/shared/httpd
#    command: ./shell.sh # per aprire una shell direttamente dentro alla macchina
    command: ./vendor/bin/phpunit # per lanciare direttamente la php unit
#TODO    command: ./ # per testare le api con composer postman







